### ISSUE TITLE
Setup error for lxml on Windows

### ISSUE THREAD

**Issue by xiaoxu193** [xiaoxu193/PyTeaser#17]
This is a problem with lxml package on Windows if you install with "pip install lxml", or the setup file.

```
error: Unable to find vcvarsall.bat
```

Current fix is to install lxml manually on windows using "easy_setup lxml==2.3.3" as suggested here: http://stackoverflow.com/a/9643941

**Comment by blaqvirus** [comment]
hi guys im getting this error here-
 from .. import etree
ImportError: cannot import name etree

Please assist
