### ISSUE TITLE
display python version.

### ISSUE THREAD

**Issue by AhnSeongHyun** [xiaoxu193/PyTeaser#39]
In python 2.6 version, 

ImportError: cannot import name Counter

Counter is only supported python2.7 and higher and is not available in earlier versions.

Have to display python version at github or pypi(https://pypi.python.org/pypi/pyteaser/1.0).

**Comment by xiaoxu193** [comment]
Done: https://github.com/xiaoxu193/PyTeaser/commit/2246dd390fab5797d870617ddace76ba5ac19665
