### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by erichonkanen** [xiaoxu193/PyTeaser#44]
Hello,

I am trying to play with this package and can't install it due to python 3 incompatibility from the beautifulsoup dependency. It appears beautifulsoup4 supports python 3, can we update the requirement?

**Comment by erichonkanen** [comment]
any word on this?

**Comment by voneiden** [comment]
I tweaked PyTeaser a bit to go with Shevchenko Vitaliy's Python 3 port of goose ( grangier/python-goose#220 ).

You can find it here: https://github.com/voneiden/PyTeaser/tree/py3

The new goose requires beautifulsoup4 and it's probably worth noting that the example huffingtonpost page doesn't seem to work anymore, so if you're not getting any results try some other website.

**Comment by accountup** [comment]
How to execute this code with flask or bottle server?
Thanks before.
