### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by daniela-llivina** [xiaoxu193/PyTeaser#55]
Hi,
Can I use PyTeaser to summarize a text in any language?

**Comment by mancvso** [comment]
In the source code, only the [stopwords](https://github.com/xiaoxu193/PyTeaser/blob/master/pyteaser.py#L6) is english based and the [punctuation](https://github.com/xiaoxu193/PyTeaser/blob/master/pyteaser.py#L207) may need to be adjusted.

Apart from that everything is statistical and not semantically dependant. So, yes.

**Comment by mancvso** [comment]
Oh and you are using español, recuerda eliminar tildes del texto original para eliminar diferencias en ortografía.

**Comment by daniela-llivina** [comment]
Thank you!
